import { AlertCircle, Loader2, MessageSquareText, Star } from "lucide-react";
import { useEffect, useState } from "react";

import Button from "../components/Button";
import { AvatarIntro, CTASection, SectionCard } from "../components/PremiumUI";
import { usePageTitle } from "../hooks/usePageTitle";
import { generateInterviewQuestions } from "../services/aiService";
import { fetchResumes } from "../services/resumeService";
import { getApiErrorMessage } from "../utils/apiError";
import { generateInterviewPlan } from "../utils/careerIntelligence";

const questions = [
  "Explain how you would design a rate-limited resume analysis API.",
  "Tell me about a time you debugged a difficult production-style issue.",
  "How do JWT access tokens and password hashing work together in authentication?"
];

export default function InterviewPrep() {
  usePageTitle("Interview Prep");
  const [resumes, setResumes] = useState([]);
  const [form, setForm] = useState({ target_role: "Backend Engineer", focus: "", resume_id: "" });
  const [generatedQuestions, setGeneratedQuestions] = useState([]);
  const [plan, setPlan] = useState(null);
  const [favoriteIds, setFavoriteIds] = useState([]);
  const [error, setError] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);

  useEffect(() => {
    fetchResumes()
      .then((data) => {
        setResumes(data);
        setForm((current) => ({ ...current, resume_id: data[0]?.id ? String(data[0].id) : "" }));
      })
      .catch(() => {
        setError("Using local interview prep mode. Sign in to connect saved resumes.");
      });
  }, []);

  function updateField(event) {
    setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  }

  async function handleGenerate() {
    setError("");
    setIsGenerating(true);
    try {
      if (String(form.resume_id).startsWith("local")) {
        const localPlan = generateInterviewPlan(form.target_role, form.focus);
        setPlan(localPlan);
        setGeneratedQuestions([...localPlan.technical, ...localPlan.behavioral].map((question, index) => ({
          id: `local-${index}`,
          target_role: form.target_role,
          question,
          question_type: index < localPlan.technical.length ? "technical" : "behavioral",
          suggested_answer: "Use the STAR method for behavioral answers and discuss tradeoffs, scale, and testing for technical answers.",
          tags: ["local"]
        })));
      } else {
        const data = await generateInterviewQuestions({
          target_role: form.target_role,
          focus: form.focus || null,
          resume_id: form.resume_id ? Number(form.resume_id) : null
        });
        setGeneratedQuestions(data.questions);
        setPlan(generateInterviewPlan(form.target_role, form.focus));
      }
    } catch (apiError) {
      const localPlan = generateInterviewPlan(form.target_role, form.focus);
      setPlan(localPlan);
      setGeneratedQuestions([...localPlan.technical, ...localPlan.behavioral].map((question, index) => ({
        id: `fallback-${index}`,
        target_role: form.target_role,
        question,
        question_type: index < localPlan.technical.length ? "technical" : "behavioral",
        suggested_answer: "Prepare a concise answer with context, decision, implementation, result, and lesson learned.",
        tags: ["fallback"]
      })));
      setError(`${getApiErrorMessage(apiError, "Cloud AI unavailable.")} Showing a local prep plan so you can continue.`);
    } finally {
      setIsGenerating(false);
    }
  }

  const visibleQuestions = generatedQuestions.length ? generatedQuestions : questions.map((question, index) => ({
    id: `sample-${index}`,
    target_role: "Backend Engineer",
    question,
    question_type: "sample",
    suggested_answer: "Suggested answers will be generated by the AI service.",
    tags: ["sample"],
  }));

  function toggleFavorite(id) {
    setFavoriteIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  }

  return (
    <div className="mx-auto max-w-7xl space-y-7">
      <AvatarIntro
        title={<>Hi! I&apos;m <span className="text-signal">Nia</span>, your interview prep coach</>}
        subtitle="your AI interview coach"
        cta={
          <Button variant="signal" onClick={handleGenerate} disabled={isGenerating}>
            {isGenerating ? <Loader2 className="animate-spin" size={18} aria-hidden="true" /> : <MessageSquareText size={18} aria-hidden="true" />}
            Generate interview preparation
          </Button>
        }
      >
        <p>Select your target role, add optional focus areas, and I&apos;ll generate technical questions, behavioral prompts, STAR stories, skills to revise, and a mock interview plan.</p>
      </AvatarIntro>

      <SectionCard className="grid gap-4 md:grid-cols-3">
        <label>
          <span className="text-sm font-semibold text-ink">Target role</span>
          <input className="focus-ring mt-2 w-full rounded-xl border border-line bg-white px-3 py-3 text-sm" name="target_role" value={form.target_role} onChange={updateField} />
        </label>
        <label>
          <span className="text-sm font-semibold text-ink">Focus</span>
          <input className="focus-ring mt-2 w-full rounded-xl border border-line bg-white px-3 py-3 text-sm" name="focus" value={form.focus} onChange={updateField} placeholder="AWS, Python, behavioral" />
        </label>
        <label>
          <span className="text-sm font-semibold text-ink">Resume</span>
          <select className="focus-ring mt-2 w-full rounded-xl border border-line bg-white px-3 py-3 text-sm" name="resume_id" value={form.resume_id} onChange={updateField}>
            <option value="">No resume context</option>
            {resumes.map((resume) => <option key={resume.id} value={resume.id}>{resume.original_filename}</option>)}
          </select>
        </label>
      </SectionCard>
      {error && (
        <div className="mb-6 flex gap-3 rounded-lg border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">
          <AlertCircle size={19} aria-hidden="true" />
          {error}
        </div>
      )}
      <section className="grid gap-4 lg:grid-cols-2">
        {visibleQuestions.map((question) => (
          <article key={question.id} className="flex items-start justify-between gap-4 rounded-2xl border border-line bg-white/90 p-5 shadow-sm">
            <div>
              <p className="text-sm font-semibold text-signal">{question.target_role} - {question.question_type}</p>
              <h2 className="mt-2 text-lg font-semibold text-ink">{question.question}</h2>
              <p className="mt-3 text-sm leading-6 text-graphite">
                {question.suggested_answer}
              </p>
            </div>
            <button
              className={`focus-ring rounded-lg p-2 hover:bg-amber-50 ${favoriteIds.includes(question.id) ? "bg-amber/10 text-amber" : "text-graphite"}`}
              aria-label="Favorite question"
              onClick={() => toggleFavorite(question.id)}
              type="button"
            >
              <Star size={20} fill={favoriteIds.includes(question.id) ? "currentColor" : "none"} aria-hidden="true" />
            </button>
          </article>
        ))}
      </section>
      {plan && (
        <section className="rounded-2xl border border-line bg-white/90 p-6 shadow-sm">
          <h2 className="text-xl font-semibold text-ink">Personalized roadmap</h2>
          <div className="mt-4 grid gap-4 md:grid-cols-3">
            <RoadmapList title="STAR stories" items={plan.starStories} />
            <RoadmapList title="Skills to revise" items={plan.skills} />
            <RoadmapList title="Mock interview plan" items={plan.roadmap} />
          </div>
        </section>
      )}
      <CTASection title="Practice with structure, not panic." description="Use these questions as your weekly prep plan and turn your projects into clear interview stories." action={<Button variant="mint" onClick={handleGenerate}>Start Mock Interview</Button>} />
    </div>
  );
}

function RoadmapList({ title, items }) {
  return (
    <div className="rounded-lg border border-line bg-glass/60 p-4">
      <p className="text-sm font-semibold text-ink">{title}</p>
      <div className="mt-3 space-y-2">
        {items.map((item) => (
          <p key={item} className="text-sm leading-6 text-graphite">{item}</p>
        ))}
      </div>
    </div>
  );
}
